/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ComoJugarRouteImport } from './routes/como-jugar'
import { Route as JugarRouteImport } from './routes/jugar'
import { Route as MazosRouteImport } from './routes/mazos'
import { Route as SalaCodeRouteImport } from './routes/sala.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoJugarRoute = ComoJugarRouteImport.update({
  id: '/como-jugar',
  path: '/como-jugar',
  getParentRoute: () => rootRouteImport,
} as any)
const JugarRoute = JugarRouteImport.update({
  id: '/jugar',
  path: '/jugar',
  getParentRoute: () => rootRouteImport,
} as any)
const MazosRoute = MazosRouteImport.update({
  id: '/mazos',
  path: '/mazos',
  getParentRoute: () => rootRouteImport,
} as any)
const SalaCodeRoute = SalaCodeRouteImport.update({
  id: '/sala/$code',
  path: '/sala/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/como-jugar': typeof ComoJugarRoute
  '/jugar': typeof JugarRoute
  '/mazos': typeof MazosRoute
  '/sala/$code': typeof SalaCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/como-jugar': typeof ComoJugarRoute
  '/jugar': typeof JugarRoute
  '/mazos': typeof MazosRoute
  '/sala/$code': typeof SalaCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/como-jugar': typeof ComoJugarRoute
  '/jugar': typeof JugarRoute
  '/mazos': typeof MazosRoute
  '/sala/$code': typeof SalaCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/como-jugar' | '/jugar' | '/mazos' | '/sala/$code'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/como-jugar' | '/jugar' | '/mazos' | '/sala/$code'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/como-jugar'
    | '/jugar'
    | '/mazos'
    | '/sala/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ComoJugarRoute: typeof ComoJugarRoute
  JugarRoute: typeof JugarRoute
  MazosRoute: typeof MazosRoute
  SalaCodeRoute: typeof SalaCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-jugar': {
      id: '/como-jugar'
      path: '/como-jugar'
      fullPath: '/como-jugar'
      preLoaderRoute: typeof ComoJugarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jugar': {
      id: '/jugar'
      path: '/jugar'
      fullPath: '/jugar'
      preLoaderRoute: typeof JugarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mazos': {
      id: '/mazos'
      path: '/mazos'
      fullPath: '/mazos'
      preLoaderRoute: typeof MazosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sala/$code': {
      id: '/sala/$code'
      path: '/sala/$code'
      fullPath: '/sala/$code'
      preLoaderRoute: typeof SalaCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ComoJugarRoute: ComoJugarRoute,
  JugarRoute: JugarRoute,
  MazosRoute: MazosRoute,
  SalaCodeRoute: SalaCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
